### ISSUE TITLE
add CLI features

### ISSUE THREAD

**Issue by noopkat** [noopkat/avrgirl-arduino#1]
+ [ ] `avrgirl-arduino list` - lists current serial ports available
+ [ ] `avrgirl-arduino boards` - lists currently supported boards

**Comment by noopkat** [comment]
Julian is currently working on this :)

**Comment by makenai** [comment]
Sorry, I didn't see that comment until after submitting my PR

**Comment by noopkat** [comment]
it's ok, I will create a label for this to prevent it in future. I've just been giving some peeps some space for a 'first avrgirl PR' opportunity on some of these issues.
