### ISSUE TITLE
Review Pull request on noopkat/js-stk500v1 to avoid problems in a Chrome Extension

### ISSUE THREAD

**Issue by tocalvo** [noopkat/avrgirl-arduino#110]
Hi :wave:, i send a pull request to https://github.com/noopkat/js-stk500v1/pull/1 , because we have a problem with the console.log and verifyPage function. I think that maybe you don't see the pull requests on that repo. It's a small change to avoid problems when we use avrgirl-arduino inside a chrome extension. 
Thanks ! :smile:

**Comment by sandeepmistry** [comment]
Hi @tocalvo,

Do you have an example app that can be used to reproduce the issue and verify your proposed fix?

**Comment by noopkat** [comment]
Hi @tocalvo I have replied to the PR on noopkat/js-stk500v1#1 
In the meantime I'll pull this down to try to reproduce in that version of Linux.

**Comment by tocalvo** [comment]
Hi @sandeepmistry , thanks for your help, i response in the js-stk500v1 fork, about the example app, the code its here: https://github.com/bq/bitbloq-chromeapp , to reproduce it, you can install the extension from here: https://chrome.google.com/webstore/detail/bitbloq/ddpdpmibfdhifigignfdiggfbcmfblfj and i just get the error on a specific educational distro called Guadalinex Edu , you can download it from here: http://www.juntadeandalucia.es/educacion/cga/portal/?page_id=7613 .
The easy way to check this, its creating and account on [Bitbloq](http://bitbloq.org) and activate the online compilation to force the use of the chrome extension.

These are some screenshots of the error:

![screen shot 2017-04-17 at 10 04 58](https://cloud.githubusercontent.com/assets/8112451/25083262/679c35b4-2356-11e7-9803-d7ffaa3f4064.png)

![screen shot 2017-04-17 at 10 05 36](https://cloud.githubusercontent.com/assets/8112451/25083273/76a2d270-2356-11e7-95f7-fa42b111c083.png)

Thanks!!

**Comment by tocalvo** [comment]
Hi! Just a reminder for the pull request on the stk500 (the error detected on the PR was solved :D )
https://github.com/noopkat/js-stk500v1/pull/1
And sorry to write about this here. I dont want to bother, its just because the last time you can't see PR on your js-stk500v1 fork.  
Thanks!
