### ISSUE TITLE
Upgrade serialport dependency

### ISSUE THREAD

**Issue by noopkat** [noopkat/avrgirl-arduino#145]
## Description

Latest version of Serialport does not work with this library. Not sure if serialport end or stk500v2 end or avrgirl-arduino end.

Going to investigate and fix this as soon as possible! This issue is tracking this work.

![bitmoji](https://render.bitstrips.com/v2/cpanel/4a148723-fbbf-4972-8e6e-120148c5a497-01e208eb-dd84-4f55-b40d-40123903eb89-v1.png?transparent=1&palette=1&width=246)

**Comment by phptuts** [comment]
So I figured out what was going on.  It's that SerialPort.list returns a promise.  I created a fix for it on fork, but I could not fix the tests.

https://github.com/phptuts/avrgirl-arduino/blob/master/lib/connection.js#L186

**Comment by phptuts** [comment]
Hope this helps, sorry could not fix the tests.

**Comment by noopkat** [comment]
closing as we have upgraded to serialport 8 at this stage
