### ISSUE TITLE
Auto-detecting boards not working on OSX El Capitan

### ISSUE THREAD

**Issue by noopkat** [noopkat/avrgirl-arduino#17]
This is a serialport issue https://github.com/voodootikigod/node-serialport/issues/552

If you specify the port, avrgirl-arduino will work just fine. This bug will be resolved once node-serialport is fixed. Sorry for the inconvenience :disappointed:

**Comment by ArekSredzki** [comment]
Fixed by voodootikigod/node-serialport#607

**Comment by ArekSredzki** [comment]
Merging #20 will fix this

**Comment by noopkat** [comment]
thanks @ArekSredzki! I wasn't home tonight, so haven't had a chance to pull it down and get it merged. Looking at it now 😁

**Comment by ArekSredzki** [comment]
No worries :smile:

**Comment by noopkat** [comment]
@ArekSredzki merged and published! Looking at #22 now
