### ISSUE TITLE
add url to product page for each board

### ISSUE THREAD

**Issue by noopkat** [noopkat/avrgirl-arduino#174]
## Description

We should introduce a new property to the boards.js list which is a string url to the product page of each board, suggested by @nnja ✨ 

## Why?

This would be really handy for both contributors to understand what all of the boards are, and also for helpful error output if a board cannot be autosniffed (we can ask the user to verify that specific board with a link to the product page)

**Comment by Lisiadito** [comment]
With product page you mean this for example [Store Arduino UNO](https://store.arduino.cc/arduino-uno-rev3) ?
I would be willing to do that.

**Comment by noopkat** [comment]
@Lisiadito totally! Let me know if you run into tricky issues sourcing the right URLs. Some of the boards we support in avrgirl are no longer in circulation / available to buy. An info page would suffice if a buy link doesn't work.

Thank you! 😄

**Comment by Lisiadito** [comment]
@noopkat I've found for most boards a page (buy or info). But I can't find a info page about the old ardunio nano.

**Comment by noopkat** [comment]
@Lisiadito this is exactly the board I was thinking would give you the trouble 😂 
I'll dig around for a suitable replacement. Thanks for the update!

**Comment by noopkat** [comment]
@Lisiadito ok let me know if this is a silly idea to you, but I found the [original Nano hardware info page](https://web.archive.org/web/20150813095112/https://www.arduino.cc/en/Main/ArduinoBoardNano) from the Internet Archive and think this would be the most accurate we can find and still from the official website?

**Comment by Lisiadito** [comment]
@noopkat hahaha I did exactly the same yesterday but wasn't sure if that's the best solution. But if that's the only link we both find I guess it's the best shot. I will add it and make the PR

**Comment by Lisiadito** [comment]
I think this can be closed since the PR is merged.
