### ISSUE TITLE
allow esnext by removing gulp

### ISSUE THREAD

**Issue by knitcodemonkey** [noopkat/avrgirl-arduino#178]
## Description

Allow JSX syntax by replacing jshint with eslint, and replacing incompatible gulp-tape package with a tape script.

### Expected behaviour

Contributor should be able to use JSX. 

### Actual behaviour

gulp-tape and jshint error when using jsx syntax

## Operating system and version

Darwin Macs-MacBook-Pro-2.local 18.7.0 Darwin Kernel Version 18.7.0: Tue Aug 20 16:57:14 PDT 2019; root:xnu-4903.271.2~2/RELEASE_X86_64 x86_64

_For information on the specific distribution. Please consult your distribution documentation._

## Avrgirl Arduino version

avrgirl-arduino@3.0.2

## NodeJS version

v10.15.3

**Comment by noopkat** [comment]
we can close this now 🎉
