### ISSUE TITLE
Web serial demo feedback

### ISSUE THREAD

**Issue by MichaelE1** [noopkat/avrgirl-arduino#190]
Hi Suz! I had a chance to mess around with the web serial demo today. It's working really well. The only issue I ran into was that a flag needs to be enabled in Chrome stable for web serial support. I've opened a [PR](https://github.com/noopkat/avrgirl-arduino/pull/189) in hope that it will save someone the time I spent debugging 😅 

I also had a go at quickly converting the demo to [React](https://github.com/MichaelE1/web-serial-react). The code is a bit messy, but the great news is that it also works. This is using the UMD AvrGirl Arduino library distribution as opposed to the global window version too!

No pic, no proof:

![webserial](https://user-images.githubusercontent.com/21051488/73114917-cf95b680-3f6a-11ea-9f90-d54808da4b49.gif)

( :

**Comment by noopkat** [comment]
Hi @MichaelE1 
Thank you SO MUCH for testing this. I lost it at the end with the waving sloth!!!!!! This is fantastic.

I would be happy to receive the React version of the demo as a pull request if you're comfortable with the code as is? Feel free to tweak it beforehand as you said it was messy and I'd want you to be happy with it. I'm thinking that we could have a vanilla javascript demo and then a react demo to help folks with getting up and running if they want to use an SPA framework approach. 

What do you think?

Thanks again I REALLY appreciate people testing this stuff out on their own machines. I actually had completely forgotten that I had enabled a Chrome flag for this to work so we should definitely add this to the readme in the demo directory 🙇

**Comment by noopkat** [comment]
Edit: just saw you opened a PR already 🤦‍♂  I'll take a look at it
