### ISSUE TITLE
Align CLI functions with API?

### ISSUE THREAD

**Issue by rwaldron** [noopkat/avrgirl-arduino#41]
Just noticed this in the readme: 

```
avrgirl-arduino list
```

vs. 

```js
Avrgirl.listPorts(function(err, ports) {
...
});
```

I would happily submit a patch that _aliases_ `Avrgirl.list` => `Avrgirl.listPorts`, if such a feature was desired. (Also can do on the other `avrgirl-*` modules)

**Comment by noopkat** [comment]
@rwaldron please do, this makes a heck of a lot of sense thank you! :clap: 
I held off on adding CLI access to the other modules until things settled on this repo with the API so we're good there.

**Comment by rwaldron** [comment]
Ok, cool—I'll try to get this done today
